config/routes.rb
Rails.application.routes.draw do

  resources :diezmosems

  resources :ofrendasems

  resources :servicios

  resources :otrosings

  resources :eventos

  resources :diezmoanuals

  resources :diezmotris

  resources :diezmodia

  resources :ofrendanuals

  resources :ofrendatris

  resources :ofrendadia

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  resources :events

  resources :p_trabajos

  resources :cancions do
      resources :letracancs
  end

  resources :directivas do
       resources :modulos
       resources :p_trabajos
  end

  resources :miembrs

  get 'paginaeg/egresos'

  get 'paginain/ingresos'

  get 'paginadi/diezmo'

  get 'pagina/ofrenda'

  get 'static_pages/ofrenda'

  

  resources :directivas

  match '/biblia', to: 'static_pages#biblia',  via: 'get'
  resources :cancions

  resources :membrecia

  root 'cancions#index'

  get 'totalofrendasemanal', to: "ofrendasems#insert_ofrendasems", as: 'totalofrendasemanal'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
   def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
        can :read, :all
        can :create, :all
        can :update, :all
        can :destroy, :all
    else user.usuario?
        #operaciones para leer algunas vistas
        can :read, Directiva
        can :read, Cancion
        can :read, Membrecium
        can :read, Modulo

   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/cancion.rb
class Cancion < ActiveRecord::Base
	def self.search(search, page)
		where(['upper(Cancion) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 3).order("Cancion")
   end
   

     validates :cancion, uniqueness: { message: "cancion ingresada ya existe" }
     validates :letra, uniqueness: { message: "letra ingresada ya existe" }


end

app/models/diezmoanual.rb
class Diezmoanual < ActiveRecord::Base
end

app/models/diezmodium.rb
class Diezmodium < ActiveRecord::Base
end

app/models/diezmosem.rb
class Diezmosem < ActiveRecord::Base
end

app/models/diezmotri.rb
class Diezmotri < ActiveRecord::Base
end

app/models/directiva.rb
class Directiva < ActiveRecord::Base
   has_many :modulos
   has_many :p_trabajos
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/evento.rb
class Evento < ActiveRecord::Base
end

app/models/membrecium.rb
class Membrecium < ActiveRecord::Base
has_many :modulos
	

	def self.search(search, page)
		where(['upper(nombre) like ?',
			"%#{search}%".upcase]).paginate(page: page, per_page: 3).order("nombre")
	end
has_attached_file :cover, :styles  =>  {  :medium  =>  "600x600>" ,  :thumb  =>  "300x300>"  },  :default_url  =>  "/images/:style/foto.png"
validates_attachment_content_type :cover, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/modulo.rb
class Modulo < ActiveRecord::Base
  belongs_to :directiva
  belongs_to :membrecium
end

app/models/ofrendasem.rb
class Ofrendasem < ActiveRecord::Base
   def self.search(search, page)
    where(['upper(valor) like ?',
    "%#{search}%".upcase]).paginate(page: page, per_page: 3).order("valor")
   end


   def cargar_ofrendasem(valor)
       ofrendasems = Ofrendasem.new
       ofrendasems.valor = valor.to_i
       ofrendasems.dia = Time.now.to_s
       ofrendasems.save
   end

end

app/models/ofrendatri.rb
class Ofrendatri < ActiveRecord::Base
end

app/models/otrosing.rb
class Otrosing < ActiveRecord::Base
end

app/models/p_trabajo.rb
class PTrabajo < ActiveRecord::Base
  belongs_to :directiva
end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
end

app/models/paginadi.rb
class Paginadi < ActiveRecord::Base
end

app/models/paginaeg.rb
class Paginaeg < ActiveRecord::Base
end

app/models/paginain.rb
class Paginain < ActiveRecord::Base
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!
	    validates :password, length: { minimum: 3 }
		validates :password, confirmation: true
		validates :password_confirmation, presence: true

		validates :email, uniqueness: true

     scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0 "} }

     ROLES = %w[admin usuario]

     def roles=(roles)
       self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
     end

     def roles
       ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
     end

     def role?(role)
       roles.include? role.to_s
     end
end

app/controllers/diezmoanuals_controller.rb
class DiezmoanualsController < ApplicationController
  before_action :set_diezmoanual, only: [:show, :edit, :update, :destroy]

  # GET /diezmoanuals
  # GET /diezmoanuals.json
  def index
    @diezmoanuals = Diezmoanual.all
  end

  # GET /diezmoanuals/1
  # GET /diezmoanuals/1.json
  def show
    @diezmoanuals = Diezmoanual.find(params[:id])
  end

  # GET /diezmoanuals/new
  def new
    @diezmoanual = Diezmoanual.new
  end

  # GET /diezmoanuals/1/edit
  def edit
    @diezmoanuals = Diezmoanual.find(params[:id])
  end

  # POST /diezmoanuals
  # POST /diezmoanuals.json
  def create
    @diezmoanual = Diezmoanual.new(diezmoanual_params)
    render action: :new unless @diezmoanual.save
  end

  # PATCH/PUT /diezmoanuals/1
  # PATCH/PUT /diezmoanuals/1.json
  def update
        render action: :edit unless @diezmoanual.update_attributes(diezmoanual_params)
  end

  # DELETE /diezmoanuals/1
  # DELETE /diezmoanuals/1.json
  def destroy
    @diezmoanual.destroy
    respond_to do |format|
      format.html { redirect_to diezmoanuals_url, notice: 'Diezmoanual was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diezmoanual
      @diezmoanual = Diezmoanual.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diezmoanual_params
      params.require(:diezmoanual).permit(:valor, :año)
    end
end

app/helpers/diezmoanuals_helper.rb
module DiezmoanualsHelper
end

app/views/diezmoanuals/_diezmoanual.html.erb
<tr id=<%="diezmoanual_#{diezmoanual.id}"%>>
       <tr>
        <td><%= link_to diezmoanual.id, diezmoanual_path(diezmoanual) %></td>
        <td><%= diezmoanual.valor %></td>
        <td><%= diezmoanual.año %></td>
        <td><%=l diezmoanual.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_diezmoanual_path(diezmoanual), remote: true, :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      diezmoanual_path(diezmoanual),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    

app/views/diezmoanuals/_form.html.erb
<%= simple_form_for(@diezmoanual, :html => { :class => 'form-horizontal', remote: true } ) do |f| %>
  <%= f.input :valor %>
  <%= f.input :año %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                diezmoanuals_path, :class => 'btn' %>
  </div>
<% end %>

app/views/diezmoanuals/_show.html.erb
<%- model_class = Diezmoanual -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:valor) %>:</strong></dt>
  <dd><%= @diezmoanual.valor %></dd>
  <dt><strong><%= model_class.human_attribute_name(:año) %>:</strong></dt>
  <dd><%= @diezmoanual.año %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              diezmoanuals_path, remote: true, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_diezmoanual_path(@diezmoanual), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              diezmoanual_path(@diezmoanual),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/diezmoanuals/create.js.erb
$('table tbody').append("<%= escape_javascript(render @diezmoanual) %>")
$.lazybox.close()

app/views/diezmoanuals/edit.js.erb
$.lazybox("<%= j(render :partial => 'form') %>", {klass: 'custom'});

app/views/diezmoanuals/index.html.erb
<%- model_class = Diezmoanual -%>
<div class="diezmoanual">
<div class="page-header">
  <h1><%=t '.title', :default => 'Diezmo Anual' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:valor) %></th>
      <th><%= model_class.human_attribute_name(:año) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
      <%= render @diezmoanuals %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_diezmoanual_path, remote: true,
            :class => 'btn btn-primary' %>


<br>

Valor Recaudado :<%= Diezmoanual.sum(:valor) %>