config/routes.rb
Rails.application.routes.draw do

  resources :diezmosems

  resources :ofrendasems

  resources :servicios

  resources :otrosings

  resources :eventos

  resources :diezmoanuals

  resources :diezmotris

  resources :diezmodia

  resources :ofrendanuals

  resources :ofrendatris

  resources :ofrendadia

  resources :user_sessions
  resources :users

  get 'login' => 'user_sessions#new', :as => :login
  get 'logout' => 'user_sessions#destroy', :as => :logout

  get 'user_sessions/new'

  get 'user_sessions/create'

  get 'user_sessions/destroy'

  resources :users

  resources :events

  resources :p_trabajos

  resources :cancions do
      resources :letracancs
  end

  resources :directivas do
       resources :modulos
       resources :p_trabajos
  end

  resources :miembrs

  get 'paginaeg/egresos'

  get 'paginain/ingresos'

  get 'paginadi/diezmo'

  get 'pagina/ofrenda'

  get 'static_pages/ofrenda'

  

  resources :directivas

  match '/biblia', to: 'static_pages#biblia',  via: 'get'
  resources :cancions

  resources :membrecia

  root 'cancions#index'

  get 'totalofrendasemanal', to: "ofrendasems#insert_ofrendasems", as: 'totalofrendasemanal'

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
   def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.admin?
        can :read, :all
        can :create, :all
        can :update, :all
        can :destroy, :all
    else user.usuario?
        #operaciones para leer algunas vistas
        can :read, Directiva
        can :read, Cancion
        can :read, Membrecium
        can :read, Modulo

   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/cancion.rb
class Cancion < ActiveRecord::Base
	def self.search(search, page)
		where(['upper(Cancion) like ?',
		"%#{search}%".upcase]).paginate(page: page, per_page: 3).order("Cancion")
   end
   

     validates :cancion, uniqueness: { message: "cancion ingresada ya existe" }
     validates :letra, uniqueness: { message: "letra ingresada ya existe" }


end

app/models/diezmoanual.rb
class Diezmoanual < ActiveRecord::Base
end

app/models/diezmodium.rb
class Diezmodium < ActiveRecord::Base
end

app/models/diezmosem.rb
class Diezmosem < ActiveRecord::Base
end

app/models/diezmotri.rb
class Diezmotri < ActiveRecord::Base
end

app/models/directiva.rb
class Directiva < ActiveRecord::Base
   has_many :modulos
   has_many :p_trabajos
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/evento.rb
class Evento < ActiveRecord::Base
end

app/models/membrecium.rb
class Membrecium < ActiveRecord::Base
has_many :modulos
	

	def self.search(search, page)
		where(['upper(nombre) like ?',
			"%#{search}%".upcase]).paginate(page: page, per_page: 3).order("nombre")
	end
has_attached_file :cover, :styles  =>  {  :medium  =>  "600x600>" ,  :thumb  =>  "300x300>"  },  :default_url  =>  "/images/:style/foto.png"
validates_attachment_content_type :cover, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/modulo.rb
class Modulo < ActiveRecord::Base
  belongs_to :directiva
  belongs_to :membrecium
end

app/models/ofrendasem.rb
class Ofrendasem < ActiveRecord::Base
   def self.search(search, page)
    where(['upper(valor) like ?',
    "%#{search}%".upcase]).paginate(page: page, per_page: 3).order("valor")
   end


   def cargar_ofrendasem(valor)
       ofrendasems = Ofrendasem.new
       ofrendasems.valor = valor.to_i
       ofrendasems.dia = Time.now.to_s
       ofrendasems.save
   end

end

app/models/ofrendatri.rb
class Ofrendatri < ActiveRecord::Base
end

app/models/otrosing.rb
class Otrosing < ActiveRecord::Base
end

app/models/p_trabajo.rb
class PTrabajo < ActiveRecord::Base
  belongs_to :directiva
end

app/models/pagina.rb
class Pagina < ActiveRecord::Base
end

app/models/paginadi.rb
class Paginadi < ActiveRecord::Base
end

app/models/paginaeg.rb
class Paginaeg < ActiveRecord::Base
end

app/models/paginain.rb
class Paginain < ActiveRecord::Base
end

app/models/servicio.rb
class Servicio < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	authenticates_with_sorcery!
	    validates :password, length: { minimum: 3 }
		validates :password, confirmation: true
		validates :password_confirmation, presence: true

		validates :email, uniqueness: true

     scope :with_role, lambda { |role| {:conditions => "roles_mask & #{2**ROLES.index(role.to_s)} > 0 "} }

     ROLES = %w[admin usuario]

     def roles=(roles)
       self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
     end

     def roles
       ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
     end

     def role?(role)
       roles.include? role.to_s
     end
end

app/controllers/directivas_controller.rb
class DirectivasController < ApplicationController
  before_action :set_directiva, only: [:show, :edit, :update, :destroy]


  # GET /directivas
  # GET /directivas.json
  def index
    @directivas = Directiva.all
  end

  # GET /directivas/1
  # GET /directivas/1.json
  def show
  end

  # GET /directivas/new
  def new
    @directiva = Directiva.new
  end

  # GET /directivas/1/edit
  def edit
    @directiva = Directiva.find(params[:id])
     unauthorized! if cannot? :edit, @directiva
  end

  # POST /directivas
  # POST /directivas.json
  def create
    @directiva = Directiva.new(directiva_params)

    respond_to do |format|
      if @directiva.save
        format.html { redirect_to @directiva, notice: 'Directiva Creada Exitosamente.' }
        format.json { render :show, status: :created, location: @directiva }
      else
        format.html { render :new }
        format.json { render json: @directiva.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directivas/1
  # PATCH/PUT /directivas/1.json
  def update
    respond_to do |format|
      if @directiva.update(directiva_params)
        format.html { redirect_to @directiva, notice: 'Directiva Modificada Exitosamente.' }
        format.json { render :show, status: :ok, location: @directiva }
      else
        format.html { render :edit }
        format.json { render json: @directiva.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directivas/1
  # DELETE /directivas/1.json
  def destroy
    @directiva.destroy
    respond_to do |format|
      format.html { redirect_to directivas_url, notice: 'Directiva Eliminada Exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directiva
      @directiva = Directiva.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directiva_params
      params.require(:directiva).permit(:nombre, :descripcion)
    end
end

app/helpers/directivas_helper.rb
module DirectivasHelper
end

app/views/directivas/_form.html.erb
<%= simple_form_for @directiva, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :nombre %>
  <%= f.input :descripcion %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                directivas_path, :class => 'btn' %>
  </div>
<% end %>

app/views/directivas/edit.html.erb
<%- model_class = Directiva -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/directivas/index.html.erb
<br>
<br>
<%- model_class = Directiva -%>
<div class="page-header">
  <center><h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1></center>
</div>
<table class="table table-striped">
  <thead>
    <tr>
    <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nombre) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>

  <tbody>
  
         
    <% @directivas.each do |directiva| %>

      <tr>
        <td><%=link_to 'Examinar =>'+ directiva.modulos.count.to_s + '',directiva_modulos_path(directiva), :class => 'btn btn-default' %></td>
        <td><%= link_to directiva.id, directiva_path(directiva) %></td>
        <td><%=link_to directiva.nombre %></td>
        <td><%= directiva.descripcion %></td>
        <td><%=l directiva.created_at %></td>
        <td>
          
          <% if can? :update, directiva %>
          <td><%= link_to t('.edit', :default => t("helpers.links.Editar")),
                      edit_directiva_path(directiva), :class => 'btn btn-success' %></td>
          <%end%>
          
          <% if can? :destroy, directiva %>
          <td><%= link_to t('.destroy', :default => t("helpers.links.Eliminar")),
                      directiva_path(directiva),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirmar", :default => 'Esta Seguro de Eliminar Directiva?')) },
                      :class => 'btn btn-mini btn-danger' %><td>
              
          <%end%>
          <%= link_to 'Plan De Trabajo', directiva_p_trabajos_path(directiva), :class => 'btn btn-info' %>
          
        </td>

    
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, @directiva %>
<%= link_to t('.new', :default => t("helpers.links.nueva Directiva")),
            new_directiva_path,
            :class => 'btn btn-primary' %>
<%end%>

app/views/directivas/new.html.erb
<%- model_class = Directiva -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/directivas/show.html.erb
<%- model_class = Directiva -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nombre) %>:</strong></dt>
  <dd><%= @directiva.nombre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @directiva.descripcion %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              directivas_path, :class => 'btn'  %>

</div>